### ISSUE TITLE
build test error: undefined reference to `printf_s'

### ISSUE THREAD

**Issue by edsiper** [QuantumLeaps/lock-free-ring-buffer#4] opened 2022-06-08 19:04 UTC
there is an undefined function in the test file:

```
/usr/bin/ld: build/sutest.o: in function `TEST':
/coding/lock-free-ring-buffer/test/sutest.c:56: undefined reference to `printf_s'
/usr/bin/ld: /coding/lock-free-ring-buffer/test/sutest.c:54: undefined reference to `printf_s'
```

**Comment by quantum-leaps** [comment] 2022-06-08 19:37
You probably tried to build it on Linux or macOS (not Windows)...
But anyway, the file `sutest.c` has been changed to use only standard `printf()`, not the safe version.
Please don't complain that the "unsafe" printf() is used...
--MMS

**Comment by edsiper** [comment] 2022-06-08 21:57
thanks for the update.

btw, is the library suitable to pass a memory address as a message (64 bit) ?

**Comment by quantum-leaps** [comment] 2022-06-09 15:24
The LFRB (Lock-Free Ring Buffer) should work with 64-bit elements, such as pointers on a 64-bit CPU. A section in [REDME](https://github.com/QuantumLeaps/lock-free-ring-buffer#code-structure) talks about it.
--MMS

**Comment by quantum-leaps** [comment] 2023-02-26 21:12
This original issue with `printf_s()` missing in `sutest` has been resolved by moving to the [Embedded-Test](https://github.com/QuantumLeaps/Embedded-Test) framework. With this comment, the issue is closed.

**Closed as completed by quantum-leaps** 2023-02-26 21:12 UTC
