### ISSUE TITLE
Lock-free as in "does not need locks" or "does not use locks but needs some"?

### ISSUE THREAD

**Issue by hartwork** [QuantumLeaps/lock-free-ring-buffer#6] opened 2023-02-05 03:15 UTC
Hi!

I ran into this project because of being advertised as "lock-free". I have two threads, one only putting things in, one only taking things out. Is that expected to be thread safe without locking on my part with lock-free-ring-buffer?

In my stress tests, it doesn't look like it. Am I misunderstanding something?
Here's the patch I applied for simple stress testing:

```diff
diff --git a/test/test_ring_buf.c b/test/test_ring_buf.c
index a2c5bc8..ed94d8e 100644
--- a/test/test_ring_buf.c
+++ b/test/test_ring_buf.c
@@ -14,11 +14,14 @@
 ============================================================================*/
 #include <stdint.h>
 #include <stdbool.h>
+#include <stdio.h>
+#include <threads.h>
 
 #include "ring_buf.h"
 #include "et.h" /* ET: embedded test */
 
-RingBufElement buf[8];
+#define STRESS_ROUNDS 10
+RingBufElement buf[65535];
 RingBuf rb;
 
 /* ring-buffer "handler" function for RingBuf_process_all() */
@@ -40,6 +43,23 @@ void teardown(void) {
     /* executed after *every* non-skipped and non-failing test */
 }
 
+int push(void* thr_data) {
+    (void)thr_data;
+    for(size_t n = 0; n < ARRAY_NELEM(buf); ++n) {
+        RingBuf_put(&rb, n);
+    }
+    return 0;
+}
+
+int pop(void* thr_data) {
+    (void)thr_data;
+    RingBufElement el;
+    for(size_t n = 0; n < ARRAY_NELEM(buf); ++n) {
+        RingBuf_get(&rb, &el);
+    }
+    return 0;
+}
+
 /* test group --------------------------------------------------------------*/
 TEST_GROUP("lock-free ring buffer") {
 
@@ -49,6 +69,29 @@ TEST("RingBuf_num_free") {
     VERIFY(RingBuf_num_free(&rb) == ARRAY_NELEM(buf) - 1U);
 }
 
+TEST("consumer-producer stress test") {
+    bool success = true;
+    for(int i = 0; i < STRESS_ROUNDS; ++i) {
+        thrd_t thr[2];
+        thrd_create(&thr[0], push, NULL);
+        thrd_create(&thr[1], pop, NULL);
+        for(int n = 0; n < 2; ++n)
+            thrd_join(thr[n], NULL);
+
+        const RingBufCtr actual = RingBuf_num_free(&rb);
+        const RingBufCtr expected = ARRAY_NELEM(buf) - 1U;
+        const bool equal = (actual == expected);
+        const char * comp = equal ? "==" : "!=";
+        printf("  [%d] %5d %s %5d\n", i, actual, comp, expected);
+        success = success && (actual == expected);
+        if (!equal) {
+            RingBufElement el;
+            while(RingBuf_get(&rb, &el)) {}
+        }
+    }
+    VERIFY(success);
+}
+
 TEST("RingBuf_put 3") {
     RingBuf_put(&rb, 0xAAU);
     RingBuf_put(&rb, 0xBBU);
```

With that patch I get output like this:
```console
# make -C test/
make: Entering directory '/tmp/tmp.wB4MgZrviN/lock-free-ring-buffer/test'
build/test_ring_buf

ET embedded test 1.0.0, https://github.com/QuantumLeaps/ET
---------------- group: lock-free ring buffer -----------------
[1] "RingBuf_num_free" .. PASSED
[2] "consumer-producer stress test" .  [0]     0 != 65534
  [1] 45068 != 65534
  [2] 32178 != 65534
  [3] 22905 != 65534
  [4] 53384 != 65534
  [5] 64896 != 65534
  [6] 65534 == 65534
  [7] 65534 == 65534
  [8] 31958 != 65534
  [9] 49910 != 65534
 FAILED
--> lock-free ring buffer:092 success
------------ 2 test(s), 0 skipped -------------
FAILED
make: *** [Makefile:155: run] Error 255
make: Leaving directory '/tmp/tmp.wB4MgZrviN/lock-free-ring-buffer/test'

```

This is on x64 hardware. Is my test violating any of the documented constraints or requirements?  What do you think?

Thanks and best, Sebastian

**Comment by quantum-leaps** [comment] 2023-02-06 15:38
Hi Sebastian,
Good idea to stress test the ring-buffer. I need to look in detail into your test, but at first glance, I count more than two threads here: producer, consumer, and the main thread. Also, the threads are spawned in a loop and I'm not sure that they terminate in the same iteration (so even more threads?) This can violate the assumption of a single producer and single consumer. Could you please check?
--MMS

**Comment by hartwork** [comment] 2023-02-06 15:48
> Hi Sebastian, Good idea to stress test the ring-buffer. I need to look in detail into your test, but at first glance, I count more than two threads here: producer, consumer, and the main thread.

HI @quantum-leaps , true, but the main thread is neither a producer nor a consumer. It does clean the ring buffer only at a time when there are no other running threads and only to give the next round a chance at producing correct results i.e. to start with an empty buffer again.

> Also, the threads are spawned in a loop and I'm not sure that they terminate in the same iteration (so even more threads?) This can violate the assumption of a single producer and single consumer. Could you please check? --MMS

In the innermost loop, there are two threads spawned through `thrd_create` — one consumer plus one producer — and two threads joined — waiting until their self-termination — through `thrd_join`. The outer loop starts at 0 threads besides the main one and ends with 0 threads besides the main one. Therefore I believe it is not violating the the  single producer and single consumer requirements. What do you think?

**Comment by zhuker** [comment] 2023-02-20 08:07
confirmed on linux x64 in c++
```
int main() {
    for (int i = 0; i < 10; i++) {
        RingBufElement buf[65535];
        RingBuf rb;
        RingBuf_ctor(&rb, buf, ARRAY_NELEM(buf));
        std::thread t([&rb]() {
            for (size_t n = 0; n < ARRAY_NELEM(buf); ++n) {
                RingBuf_put(&rb, n);
            }
        });
        std::thread t2([&rb]() {
            RingBufElement el;
            for (size_t n = 0; n < ARRAY_NELEM(buf); ++n) {
                RingBuf_get(&rb, &el);
            }
        });
        t.join();
        t2.join();
        RingBufCtr actual = RingBuf_num_free(&rb);
        RingBufCtr expected = ARRAY_NELEM(buf) - 1U;
        printf("%d %d\n", expected, actual);
    }
}
```

output is:
```
65534 65534
65534 35163
65534 65534
65534 65534
65534 65534
65534 59864
65534 65368
65534 65534
65534 58512
65534 65534

```

**Comment by fun-works** [comment] 2023-02-26 17:16
So it is failing on linux 64 bit ?

**Comment by quantum-leaps** [comment] 2023-02-26 20:47
I'm still not sure this whole "stress test" is legit.  Starting and "joining" so many threads might violate the assumption of a single producer and a single consumer. Also, why would any such test fail only for index==65534==0xFFFE ? Can anybody explain?

**Comment by hartwork** [comment] 2023-02-27 00:05
> Starting and "joining" so many threads might violate the assumption of a single producer and a single consumer.

While both @zhuker and me used three threads in our examples when taking the main thread into account, both his and my code are easy to adapt into a version with only two threads. The outer loop has no effect on the number of threads running in parallel, it only tries the same thing multiple times.

> Also, why would any such test fail only for index==65534==0xFFFE ? Can anybody explain?

A big number works as an amplifier meaning that it increases the chance to see the race condition happen. You can also observe this with 65530, it just becomes a bit less likely. In that sense there is nothing magic about 65534.

**Comment by quantum-leaps** [comment] 2023-02-27 01:20
> both his and my code are easy to adapt into a version with only two threads.

I think such a test would be much cleaner, so if you could come up with a test that relies on only one producer thread and one consumer thread, I would have to accept your test results. For now, I think that your "stress test" simply causes some misalignment between the multiple producers and consumers, as the threads are killed before they actually produce or consume. So, by all means, please prove me wrong.

**Comment by hartwork** [comment] 2023-02-27 02:10
Hi @quantum-leaps,

alright, I made it use only two threads now.

The output for the new code is something like this, amount varies per run:
```
# make -C test/
make: Entering directory '/tmp/tmp.vYPAi8C9xy/lock-free-ring-buffer/test'
build/test_ring_buf

ET embedded test 2.0.0, https://github.com/QuantumLeaps/ET
---------------- group: lock-free ring buffer -----------------
[1] "RingBuf_num_free" .. PASSED
[2] "consumer-producer stress test" .
  [  20] 64239 != 65535
  [  31] 65340 != 65535
  [ 353] 54980 != 65535
  [ 485] 62655 != 65535
  [ 570] 64975 != 65535
  [ 939] 65234 != 65535
  Failed 6 times out of 1000 (~= 0.60 %).
 FAILED
--> lock-free ring buffer:097 times_failed == 0
------------ 2 test(s), 0 skipped -------------
FAILED
make: *** [Makefile:155: run] Error 255
make: Leaving directory '/tmp/tmp.vYPAi8C9xy/lock-free-ring-buffer/test'
```

My new patch to produce output like that is [stress-test-demo.patch.txt](https://github.com/QuantumLeaps/lock-free-ring-buffer/files/10835474/stress-test-demo.patch.txt).

Can be applied locally using `patch -p1 < stress-test-demo.patch.txt`.

What do you think?

**Comment by hartwork** [comment] 2023-02-27 02:23
@quantum-leaps I notice now that I had a logic flaw in my test: If the code starts to pop things before available then nothing will be popped and the count will be off. So the failure above is caused by the pop thread starting sooner or later than the main thread starts to push things. Once I fix that by making the buffer half-full at start-time and then pushing  and popping half the buffer size in parallel, I can no longer reproduce the problem even for 100,000 iterations, this patch [stress-test-2.patch.txt](https://github.com/QuantumLeaps/lock-free-ring-buffer/files/10835539/stress-test-2.patch.txt).

**Comment by quantum-leaps** [comment] 2023-02-27 14:01
What's the next step then? Can we close this issue as "resolved"?

Also, currently the "stress test" patch has not been merged in. Do you think it should be? Does it add value? Is that how the ring-buffer should be tested?

Please advise.

**Comment by hartwork** [comment] 2023-02-27 16:06
@quantum-leaps I had a chance to sleep over it now and noticed that some failure to pop should have left _more_ items in the buffer not fewer, hence I believe there is something left to discover here. A stress test that doesn't find things does not prove that the code is right, only the other way around. Let me play with the code more.

What lead me to try stress testing the code in the first place is that I see nothing like ~C11 atomic datatypes or~ [compare-and-swap](https://en.wikipedia.org/wiki/Compare-and-swap) in here, nothing that would made me think "oh that's why it doesn't need locks". So independent of any stress testing code, could you elaborate what you did to make the code lock free, why you think it should survive stress tests despite no use of locks? I'd like to understand what I am missing.

**Comment by quantum-leaps** [comment] 2023-02-27 17:03
You are absolutely right that testing cannot prove the code is correct. Testing can only prove that the code is incorrect if the test shows a failure mode (but this still remains to be demonstrated for the LFRB).

> I see nothing like C11 atomic datatypes or [compare-and-swap](https://en.wikipedia.org/wiki/Compare-and-swap) in here...

I don't quite understand the expectations that some "magic" like atomic or compare-and-swap are necessary to make code "trustworthy." For example, 'volatile' has been traditionally considered a "must" but here I would recommend the paper [Why the “volatile” type class should not be used](https://www.kernel.org/doc/html/latest/process/volatile-considered-harmful.html).

> So independent of any stress testing code, could you elaborate what you did to make the code lock free...

My motivation for developing (and later sharing the LFRB on GitHub) was a deeply embedded application. Specifically, I needed a way to collect input from a primitive UART (without internal buffering such as FIFO or DMA) and then send that input for processing to an idle task (or background loop). I had to use interrupt on every delivered byte but didn't want to disable the UART interrupt as a locking mechanism because that could lead to dropping bytes (there was no buffering!). I used the LFRB algorithm extensively and didn't observe any errors. (My error detection was quite strict, as the delivered bytes were checksummed and individual packets were sequence-numbered, so I would have known about a single dropped or erroneous byte.)

> why you think it should survive stress tests despite no use of locks?

The LFRB algorithm relies on the _order_ of the updates to the ring buffer data and indexes, which are guaranteed by the [C sequence-points](https://learn.microsoft.com/en-us/cpp/c-language/c-sequence-points). Of course, there are additional assumptions about the internal indexes of the buffer, which must be updated in one CPU instruction. (So, using a 16-bit index on a 8-bit CPU would violate such assumptions.)

By the way, the LFRB tests on a low-end 16MHz embedded CPU with baud rates of 115200 bytes/s are much more _"stressful"_ than your tests with P-threads on a GHz-class desktop machine. The context switches among such P-threads are typically driven by time-slicing, which happens only every 10ms or so. This means a context switch only every ~10 billion CPU cycles. In contrast, the embedded CPU had to context-switch (handle interrupt) 11 times per millisecond, which works out to ~1000 CPU cycles between context switches. (This means that just 1s of my test was equivalent to over 100 *days* of continuous running of your test). Moreover, since the reading of the ring-buffer happened in the idle task, that task was surely hammered by the UART interrupts in question, so the test addressed the issue.

**Comment by hartwork** [comment] 2023-02-27 17:11
> I don't quite understand the expectations that some "magic" like atomic or compare-and-swap are necessary to make code "trustworthy."

@quantum-leaps if we have two threads that access the same data, I think we agree that the "normal assumption" would be that access to the shared resources needs synchronization and the classic approach would be locking. Now this project claims that no locks are needed and then my question would be: if normally _some_ synchronization be needed, what does the code do or that makes need for locks go away. There must be some answer to this, if it's just nothing, then it won't be thread-safe because the two threads can interleave arbitrarily. Does that make sense? I'm happy to learn what I am missing.

**Comment by quantum-leaps** [comment] 2023-02-27 17:24
Please see my comment about carefully ordering the updates in the LFRB and the [C sequence-points](https://learn.microsoft.com/en-us/cpp/c-language/c-sequence-points). I might have edited the comment after you posted your critique.

**Comment by hartwork** [comment] 2023-02-27 18:03
@quantum-leaps which comments where? Regarding C sequence points, I don't see how they say much beyond a single thread. What am I missing?

**Comment by quantum-leaps** [comment] 2023-02-27 18:49
Yes, naturally, "C sequence points" pertain to a single thread of execution. I mention them only because an earlier "issue" was reported for the LFRB repository (you can search for it), where the author suggested that the compiler could alter the ordering of operations. So, even though the ordering is only guaranteed for a single thread, it _is guaranteed_, so the compiler cannot change that. This ordering of updates to the internal LFRB data and indexes is sufficient to make it "lock free" (along with all the other assumptions explicitly spelled out in the README.md in this repository.)

On a side note, I don't understand the general hostility of the posts (not just yours) regarding this little algorithm. It seems to confirm the rule that no good deed goes unpunished. I hope you understand that it would be easier just to remove this repository and save a lot of my time. I keep it posted only because it could be useful to fellow software developers.

As to why I believe the thing works, I have tried to describe the design and my testing. If you believe that the LFRB algorithm (plus all the assumptions) is incorrect, the burden is on you to _prove it_.

**Comment by hartwork** [comment] 2023-02-27 19:33
> On a side note, I don't understand the general hostility of the posts (not just yours) regarding this little algorithm.

@quantum-leaps I'm not if this reply has more chance to repair things or make things worse. Either way, at least I'll have tried:

Sorry that I came across as hostile, I think I know why that is.
I consider myself skeptical, not hostile, and I'm happy to learn something and be proven wrong.

I found ticket #3 now: While the author's tone is maybe not the best, the question is legit to me and the answer there is not really answering the question, because it only covers variable atomicity not the rest of the picture.

> This ordering of updates to the internal LFRB data and indexes is sufficient to make it "lock free" (along with all the other assumptions explicitly spelled out in the README.md in this repository.)

That's what I don't understand. Why do you consider that ordering of updates sufficient? The readme only says that it is, not why, I rechecked.

> I hope you understand that it would be easier just to remove this repository and save a lot of my time. I keep it posted only because it could be useful to fellow software developers.

If it is indeed thread-safe despite being lock-free, then it's definitely useful, I could not agree more.

> As to why I believe the thing works, I have tried to describe the design and my testing. If you believe that the LFRB algorithm (plus all the assumptions) is incorrect, the burden is on you to _prove it_.

That's a question of view. What I'd agree to is that you don't owe me anything, yes, but's that's something else.
I think if someone says that something doesn't need locks it's fair to see if that is reality. That serves everyone.
I'm not here to be right, I'm here for truth.
I think my tone here was okay. Maybe not lovely but okay. If the title of the issue the problem, I just didn't find a better way to put it. I can fix the title if you have ideas for a better one.

If you feel like you want to close this ticket, please go ahead and I'll move on. Alternatively, I could contribute CI based on GitHub Actions that would prevent some future regressions. How you would to proceed?

Best, Sebastian

**Comment by quantum-leaps** [comment] 2023-02-27 19:46
Hi Sebastian,

 > How you would to proceed?

I understand that you have good intentions. But still, I'm quite busy right now and I don't have the time to argue or educate about "lock-free" data structures in C (you can just google for it).

For now, I simply change the status of this repository to "private".

If you have the time to spend on this, please by all means scrutinize it either way. Perhaps after this, the LFRB can be re-published. But for now, I'm just tired...

**Closed as completed** 2023-03-30 17:49 UTC

**Comment by pffang** [comment] 2024-08-15 01:24
Sorry to reply to this closed topic.
But this project is **not thread-safe** in modern multi-core CPUs, even for single-producer single-consumer scenario on ARM embedded SoCs. You need to think about the CPU cache and memory order.
Please read this: https://www.irif.fr/~guatto/papers/sbac13.pdf

**Comment by quantum-leaps** [comment] 2024-08-15 13:44
Hi pffang,
Thanks a lot for the notice about the advanced multi-core SoCs with complex cache memories. The presented LFRB implementation was never intended for such complex systems, but you are absolutely right that this should be crystal clear in the documentation. Consequently, I've updated the [README.md](https://github.com/QuantumLeaps/lock-free-ring-buffer/blob/main/README.md) file. The README.md file now also provides a reference to the academic paper you recommended. Please let me know if you still see a need to improve the language in the file. 

Regarding the actual LFRB implementation, it has not been modified because I'm not sure that adding "atomic_store()" operations would improve the usability of LFRB for the intended application domain (also better defined in the README file). Such "atomic_store()" operations would involve memory barrier instructions, which would reduce the portability of the code.

**Comment by pffang** [comment] 2024-08-16 11:10
I think it's fine now.

I used to develop on old MCUs before, I can make sure this project is fine for single core MCUs.
But now, more and more embedded SoCs are also increasingly using multi cores.
So people will get confused when trying this project like above guys. :)
